mklink /D "TalesWatcher\Assets\YogollagCode\Yogollag" "..\..\..\Yogollag"
mklink /D "TalesWatcher\Assets\YogollagCode\Server" "..\..\..\Server"
mklink /D "TalesWatcher\Assets\YogollagCode\ResourcesSystem" "..\..\..\ResourcesSystem"
mklink /D "TalesWatcher\Assets\YogollagCode\VolatilePhysics" "..\..\..\VolatilePhysics"
mklink /D "TalesWatcher\Assets\YogollagCode\lib" "..\..\..\GameTest\lib"
mklink /D "TalesWatcher\Assets\YogollagCode\extlibs" "..\..\..\GameTest\extlibs"
mklink "TalesWatcher\Assets\YogollagCode\Attributes.cs" "..\..\..\CodeGen\Attributes.cs"
