// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using NetworkEngine;
using CodeGen;
using SFML.Graphics;
using SFML.System;
using SFML.Window;
using System;
using System.Threading.Tasks;
using LiteNetLib.Utils;
using System.Linq;
using System.Collections.Generic;
using Volatile;
using Definitions;
using SFML.Audio;

namespace Yogollag
{
}

namespace Yogollag
{
    [GeneratedClass]
    public partial class VisibilityEntitySync
    {
        override protected void SetDefsForComponents()
        {
        }

        override public void CallInitOnComponents()
        {
        }

        override public void CallCreateOnComponents()
        {
        }

        override public void CallDestroyOnComponents()
        {
        }
    }

    //obj VisibilityEntity generic  hasCustomSerialization false
    //debug info IEntityPropertyChanged,ITicked 2
    [GeneratedClass]
    public partial class VisibilityEntitySync : VisibilityEntity, IGhost
    {
        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, 1327180956);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            OnAfterDeserialize();
        }

        public override void SetParentEntityRecursive()
        {
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, 1327180956);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            return hasAny;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public partial class SessionEntitySync
    {
        override protected void SetDefsForComponents()
        {
        }

        override public void CallInitOnComponents()
        {
        }

        override public void CallCreateOnComponents()
        {
        }

        override public void CallDestroyOnComponents()
        {
        }
    }

    //obj SessionEntity generic  hasCustomSerialization false
    //debug info IEntityPropertyChanged 1
    [GeneratedClass]
    public partial class SessionEntitySync : SessionEntity, IGhost
    {
        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, -1979716632);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            OnAfterDeserialize();
        }

        public override void SetParentEntityRecursive()
        {
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, -1979716632);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            return hasAny;
        }

        public override void Join(string name)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.Join(name);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new SessionEntityJoinMessage()
                {EntityId = Id, name = name});
            }
        }
    }

    [GeneratedClass]
    public class SessionEntityJoinMessage : EntityMessage
    {
        public override int NetId => -148817396;
        public string name;
        public override void Run(object entity)
        {
            ((SessionEntity)entity).Join(name);
        }
    }

    [GeneratedClass]
    public class SessionEntityJoinMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new SessionEntityJoinMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                messageToSerialize.name = stream.GetString();
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (SessionEntityJoinMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                stream.Put(messageToSerialize.name);
            }

            return true;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public partial class SampleComponentSync
    {
        override protected void SetDefsForComponents()
        {
        }

        override public void CallInitOnComponents()
        {
        }

        override public void CallCreateOnComponents()
        {
        }

        override public void CallDestroyOnComponents()
        {
        }
    }

    //obj SampleComponent generic  hasCustomSerialization false
    //debug info  0
    [GeneratedClass]
    public partial class SampleComponentSync : SampleComponent, IGhost
    {
        public override Vec2 Pos
        {
            get => base.Pos;
            set
            {
                base.Pos = value;
                OnPropChanged(0);
            }
        }

        public override Vec2 PrevPos
        {
            get => base.PrevPos;
            set
            {
                base.PrevPos = value;
                OnPropChanged(1);
            }
        }

        public override Int32 SyncId
        {
            get => base.SyncId;
            set
            {
                base.SyncId = value;
                OnPropChanged(2);
            }
        }

        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, 1730039601);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            CheckStream(stream, -569944260);
            if ((mask & (1 << 0)) != 0)
            {
                CheckStream(stream, -569944260);
                var has = stream.GetBool();
                Pos = !has ? default : (Vec2)SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Deserialize(stream);
                CheckStream(stream, -569944260);
            }

            CheckStream(stream, 1939843226);
            if ((mask & (1 << 1)) != 0)
            {
                CheckStream(stream, 1939843226);
                var has = stream.GetBool();
                PrevPos = !has ? default : (Vec2)SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Deserialize(stream);
                CheckStream(stream, 1939843226);
            }

            CheckStream(stream, -1219259098);
            if ((mask & (1 << 2)) != 0)
            {
                CheckStream(stream, -1219259098);
                SyncId = stream.GetInt();
                CheckStream(stream, -1219259098);
            }

            OnAfterDeserialize();
        }

        public override void SetParentEntityRecursive()
        {
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, 1730039601);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            SafeguardStream(stream, -569944260);
            if ((deltaMask & (1 << 0)) != 0)
            {
                SafeguardStream(stream, -569944260);
                hasAny = true;
                if (Pos != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Serialize(Pos, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, -569944260);
            }

            SafeguardStream(stream, 1939843226);
            if ((deltaMask & (1 << 1)) != 0)
            {
                SafeguardStream(stream, 1939843226);
                hasAny = true;
                if (PrevPos != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Serialize(PrevPos, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, 1939843226);
            }

            SafeguardStream(stream, -1219259098);
            if ((deltaMask & (1 << 2)) != 0)
            {
                SafeguardStream(stream, -1219259098);
                hasAny = true;
                stream.Put(SyncId);
                SafeguardStream(stream, -1219259098);
            }

            return hasAny;
        }

        public override void HandlePos(Vec2 newPos)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.HandlePos(newPos);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new SampleComponentHandlePosMessage()
                {EntityId = Id, newPos = newPos});
            }
        }
    }

    [GeneratedClass]
    public class SampleComponentHandlePosMessage : EntityMessage
    {
        public override int NetId => 1567557258;
        public Vec2 newPos;
        public override void Run(object entity)
        {
            ((SampleComponent)entity).HandlePos(newPos);
        }
    }

    [GeneratedClass]
    public class SampleComponentHandlePosMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new SampleComponentHandlePosMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var has = stream.GetBool();
                messageToSerialize.newPos = !has ? default : (Vec2)SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Deserialize(stream);
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (SampleComponentHandlePosMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.newPos != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Serialize(messageToSerialize.newPos, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            return true;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public partial class ItemSync
    {
        override protected void SetDefsForComponents()
        {
        }

        override public void CallInitOnComponents()
        {
        }

        override public void CallCreateOnComponents()
        {
        }

        override public void CallDestroyOnComponents()
        {
        }
    }

    //obj Item generic  hasCustomSerialization false
    //debug info IEntityObject 1
    [GeneratedClass]
    public partial class ItemSync : Item, IGhost
    {
        public override SpellId PassiveBuff
        {
            get => base.PassiveBuff;
            set
            {
                base.PassiveBuff = value;
                OnPropChanged(0);
            }
        }

        public override SpellId ActiveBuff
        {
            get => base.ActiveBuff;
            set
            {
                base.ActiveBuff = value;
                OnPropChanged(1);
            }
        }

        public override Int64 ItemId
        {
            get => base.ItemId;
            set
            {
                base.ItemId = value;
                OnPropChanged(2);
            }
        }

        public override ItemDef ItemDef
        {
            get => base.ItemDef;
            set
            {
                base.ItemDef = value;
                OnPropChanged(3);
            }
        }

        public override Int32 SyncId
        {
            get => base.SyncId;
            set
            {
                base.SyncId = value;
                OnPropChanged(4);
            }
        }

        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, -1909547482);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            CheckStream(stream, 1526530670);
            if ((mask & (1 << 0)) != 0)
            {
                CheckStream(stream, 1526530670);
                var has = stream.GetBool();
                PassiveBuff = !has ? default : (SpellId)SyncTypesMap.GetSerializerForObjType(typeof(SpellId)).Deserialize(stream);
                CheckStream(stream, 1526530670);
            }

            CheckStream(stream, 1423919529);
            if ((mask & (1 << 1)) != 0)
            {
                CheckStream(stream, 1423919529);
                var has = stream.GetBool();
                ActiveBuff = !has ? default : (SpellId)SyncTypesMap.GetSerializerForObjType(typeof(SpellId)).Deserialize(stream);
                CheckStream(stream, 1423919529);
            }

            CheckStream(stream, -514622254);
            if ((mask & (1 << 2)) != 0)
            {
                CheckStream(stream, -514622254);
                ItemId = stream.GetLong();
                CheckStream(stream, -514622254);
            }

            CheckStream(stream, 1063757487);
            if ((mask & (1 << 3)) != 0)
            {
                CheckStream(stream, 1063757487);
                var has = stream.GetBool();
                ItemDef = !has ? default : (ItemDef)SyncTypesMap.GetSerializerForObjType(typeof(ItemDef)).Deserialize(stream);
                CheckStream(stream, 1063757487);
            }

            CheckStream(stream, -1219259098);
            if ((mask & (1 << 4)) != 0)
            {
                CheckStream(stream, -1219259098);
                SyncId = stream.GetInt();
                CheckStream(stream, -1219259098);
            }

            OnAfterDeserialize();
        }

        public override void SetParentEntityRecursive()
        {
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, -1909547482);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            SafeguardStream(stream, 1526530670);
            if ((deltaMask & (1 << 0)) != 0)
            {
                SafeguardStream(stream, 1526530670);
                hasAny = true;
                if (PassiveBuff != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(SpellId)).Serialize(PassiveBuff, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, 1526530670);
            }

            SafeguardStream(stream, 1423919529);
            if ((deltaMask & (1 << 1)) != 0)
            {
                SafeguardStream(stream, 1423919529);
                hasAny = true;
                if (ActiveBuff != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(SpellId)).Serialize(ActiveBuff, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, 1423919529);
            }

            SafeguardStream(stream, -514622254);
            if ((deltaMask & (1 << 2)) != 0)
            {
                SafeguardStream(stream, -514622254);
                hasAny = true;
                stream.Put(ItemId);
                SafeguardStream(stream, -514622254);
            }

            SafeguardStream(stream, 1063757487);
            if ((deltaMask & (1 << 3)) != 0)
            {
                SafeguardStream(stream, 1063757487);
                hasAny = true;
                if (ItemDef != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(ItemDef)).Serialize(ItemDef, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, 1063757487);
            }

            SafeguardStream(stream, -1219259098);
            if ((deltaMask & (1 << 4)) != 0)
            {
                SafeguardStream(stream, -1219259098);
                hasAny = true;
                stream.Put(SyncId);
                SafeguardStream(stream, -1219259098);
            }

            return hasAny;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public partial class ItemsCollectionSync
    {
        override protected void SetDefsForComponents()
        {
        }

        override public void CallInitOnComponents()
        {
        }

        override public void CallCreateOnComponents()
        {
        }

        override public void CallDestroyOnComponents()
        {
        }
    }

    //obj ItemsCollection generic  hasCustomSerialization false
    //debug info  0
    [GeneratedClass]
    public partial class ItemsCollectionSync : ItemsCollection, IGhost
    {
        public override Int32 Size
        {
            get => base.Size;
            set
            {
                base.Size = value;
                OnPropChanged(0);
            }
        }

        public override Int64 Counter
        {
            get => base.Counter;
            set
            {
                base.Counter = value;
                OnPropChanged(1);
            }
        }

        public override DeltaList<Item> Items
        {
            get => base.Items;
            set
            {
                ((SyncObject)base.Items)?.SetParentEntity(null);
                base.Items = value;
                OnPropChanged(2);
                ((SyncObject)base.Items)?.SetParentEntity(ParentEntity);
            }
        }

        public override Int32 SyncId
        {
            get => base.SyncId;
            set
            {
                base.SyncId = value;
                OnPropChanged(3);
            }
        }

        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
            ((IGhost)Items)?.ClearSerialization();
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, -1409016881);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            CheckStream(stream, -727975383);
            if ((mask & (1 << 0)) != 0)
            {
                CheckStream(stream, -727975383);
                Size = stream.GetInt();
                CheckStream(stream, -727975383);
            }

            CheckStream(stream, 1752588651);
            if ((mask & (1 << 1)) != 0)
            {
                CheckStream(stream, 1752588651);
                Counter = stream.GetLong();
                CheckStream(stream, 1752588651);
            }

            CheckStream(stream, 1191265963);
            if ((mask & (1 << 2)) != 0)
            {
                CheckStream(stream, 1191265963);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    Items = null;
                }
                else
                {
                    var newVal = SyncObject.New<DeltaList<Item>>();
                    ((IGhost)newVal).Deserialize(stream);
                    Items = (DeltaList<Item>)newVal;
                }

                CheckStream(stream, 1191265963);
            }
            else
            {
                CheckStream(stream, 1191265963);
                ((IGhost)Items)?.Deserialize(stream);
                CheckStream(stream, 1191265963);
            }

            CheckStream(stream, -1219259098);
            if ((mask & (1 << 3)) != 0)
            {
                CheckStream(stream, -1219259098);
                SyncId = stream.GetInt();
                CheckStream(stream, -1219259098);
            }

            OnAfterDeserialize();
        }

        public override void SetParentEntityRecursive()
        {
            ((SyncObject)Items)?.SetParentEntity(this.ParentEntity);
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, -1409016881);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            SafeguardStream(stream, -727975383);
            if ((deltaMask & (1 << 0)) != 0)
            {
                SafeguardStream(stream, -727975383);
                hasAny = true;
                stream.Put(Size);
                SafeguardStream(stream, -727975383);
            }

            SafeguardStream(stream, 1752588651);
            if ((deltaMask & (1 << 1)) != 0)
            {
                SafeguardStream(stream, 1752588651);
                hasAny = true;
                stream.Put(Counter);
                SafeguardStream(stream, 1752588651);
            }

            SafeguardStream(stream, 1191265963);
            if ((deltaMask & (1 << 2)) != 0)
            {
                SafeguardStream(stream, 1191265963);
                hasAny = true;
                if (Items == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    ((IGhost)Items).Serialize(ref stream, true);
                }

                SafeguardStream(stream, 1191265963);
            }
            else
            {
                SafeguardStream(stream, 1191265963);
                hasAny |= ((IGhost)Items)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, 1191265963);
            }

            SafeguardStream(stream, -1219259098);
            if ((deltaMask & (1 << 3)) != 0)
            {
                SafeguardStream(stream, -1219259098);
                hasAny = true;
                stream.Put(SyncId);
                SafeguardStream(stream, -1219259098);
            }

            return hasAny;
        }

        public override void MakeActive(long itemId)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.MakeActive(itemId);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new ItemsCollectionMakeActiveMessage()
                {EntityId = Id, itemId = itemId});
            }
        }

        public override void MakeInactive(long itemId)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.MakeInactive(itemId);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new ItemsCollectionMakeInactiveMessage()
                {EntityId = Id, itemId = itemId});
            }
        }

        public override void DropItem(Item item)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.DropItem(item);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new ItemsCollectionDropItemMessage()
                {EntityId = Id, item = item});
            }
        }

        public override void AddItem(Item item)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.AddItem(item);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new ItemsCollectionAddItemMessage()
                {EntityId = Id, item = item});
            }
        }

        public override void RemoveItem(long itemId)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.RemoveItem(itemId);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new ItemsCollectionRemoveItemMessage()
                {EntityId = Id, itemId = itemId});
            }
        }

        public override void MoveItem(long itemId, int slot)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.MoveItem(itemId, slot);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new ItemsCollectionMoveItemMessage()
                {EntityId = Id, itemId = itemId, slot = slot});
            }
        }
    }

    [GeneratedClass]
    public class ItemsCollectionMakeActiveMessage : EntityMessage
    {
        public override int NetId => 608133504;
        public long itemId;
        public override void Run(object entity)
        {
            ((ItemsCollection)entity).MakeActive(itemId);
        }
    }

    [GeneratedClass]
    public class ItemsCollectionMakeActiveMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new ItemsCollectionMakeActiveMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                messageToSerialize.itemId = stream.GetLong();
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (ItemsCollectionMakeActiveMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                stream.Put(messageToSerialize.itemId);
            }

            return true;
        }
    }

    [GeneratedClass]
    public class ItemsCollectionMakeInactiveMessage : EntityMessage
    {
        public override int NetId => 842622839;
        public long itemId;
        public override void Run(object entity)
        {
            ((ItemsCollection)entity).MakeInactive(itemId);
        }
    }

    [GeneratedClass]
    public class ItemsCollectionMakeInactiveMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new ItemsCollectionMakeInactiveMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                messageToSerialize.itemId = stream.GetLong();
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (ItemsCollectionMakeInactiveMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                stream.Put(messageToSerialize.itemId);
            }

            return true;
        }
    }

    [GeneratedClass]
    public class ItemsCollectionDropItemMessage : EntityMessage
    {
        public override int NetId => -1869611912;
        public Item item;
        public override void Run(object entity)
        {
            ((ItemsCollection)entity).DropItem(item);
        }
    }

    [GeneratedClass]
    public class ItemsCollectionDropItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new ItemsCollectionDropItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    messageToSerialize.item = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    messageToSerialize.item = (Item)newVal;
                }
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (ItemsCollectionDropItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.item == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(messageToSerialize.item.GetType()));
                    ((IGhost)messageToSerialize.item).Serialize(ref stream, true);
                }
            }

            return true;
        }
    }

    [GeneratedClass]
    public class ItemsCollectionAddItemMessage : EntityMessage
    {
        public override int NetId => -1745315543;
        public Item item;
        public override void Run(object entity)
        {
            ((ItemsCollection)entity).AddItem(item);
        }
    }

    [GeneratedClass]
    public class ItemsCollectionAddItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new ItemsCollectionAddItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    messageToSerialize.item = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    messageToSerialize.item = (Item)newVal;
                }
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (ItemsCollectionAddItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.item == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(messageToSerialize.item.GetType()));
                    ((IGhost)messageToSerialize.item).Serialize(ref stream, true);
                }
            }

            return true;
        }
    }

    [GeneratedClass]
    public class ItemsCollectionRemoveItemMessage : EntityMessage
    {
        public override int NetId => -1551205589;
        public long itemId;
        public override void Run(object entity)
        {
            ((ItemsCollection)entity).RemoveItem(itemId);
        }
    }

    [GeneratedClass]
    public class ItemsCollectionRemoveItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new ItemsCollectionRemoveItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                messageToSerialize.itemId = stream.GetLong();
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (ItemsCollectionRemoveItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                stream.Put(messageToSerialize.itemId);
            }

            return true;
        }
    }

    [GeneratedClass]
    public class ItemsCollectionMoveItemMessage : EntityMessage
    {
        public override int NetId => -2101675;
        public long itemId;
        public int slot;
        public override void Run(object entity)
        {
            ((ItemsCollection)entity).MoveItem(itemId, slot);
        }
    }

    [GeneratedClass]
    public class ItemsCollectionMoveItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new ItemsCollectionMoveItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                messageToSerialize.itemId = stream.GetLong();
            }

            {
                messageToSerialize.slot = stream.GetInt();
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (ItemsCollectionMoveItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                stream.Put(messageToSerialize.itemId);
            }

            {
                stream.Put(messageToSerialize.slot);
            }

            return true;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public class CharacterEntitySceneDef : BaseDef, ISceneDef
    {
        public Single Rotation
        {
            get;
            set;
        }

        = default;
        public Vec2 Position
        {
            get;
            set;
        }

        = default;
        public DefRef<SpriteRendererSceneDef> _spriteRenderer
        {
            get;
            set;
        }

        = default;
        public DefRef<SpellsEngineSceneDef> SpellsEngine
        {
            get;
            set;
        }

        = default;
        public DefRef<CombatEngineSceneDef> CombatEngine
        {
            get;
            set;
        }

        = default;
        public DefRef<ActionEngineSceneDef> ActionEngine
        {
            get;
            set;
        }

        = default;
        public DefRef<StatsEngineSceneDef> StatsEngine
        {
            get;
            set;
        }

        = default;
    }

    [GeneratedClass]
    public class CharacterEntityDef : BaseDef, IEntityObjectDef
    {
        public DefRef<SpriteRendererDef> _spriteRenderer
        {
            get;
            set;
        }

        = default;
        public DefRef<SpellsEngineDef> SpellsEngine
        {
            get;
            set;
        }

        = default;
        public DefRef<CombatEngineDef> CombatEngine
        {
            get;
            set;
        }

        = default;
        public DefRef<ActionEngineDef> ActionEngine
        {
            get;
            set;
        }

        = default;
        public DefRef<StatsEngineDef> StatsEngine
        {
            get;
            set;
        }

        = default;
    }

    [GeneratedClass]
    public partial class CharacterEntitySync
    {
        override protected void SetDefsForComponents()
        {
            _spriteRenderer.Def = (IDef)((CharacterEntityDef)Def)?._spriteRenderer.Def;
            SpellsEngine.Def = (IDef)((CharacterEntityDef)Def)?.SpellsEngine.Def;
            CombatEngine.Def = (IDef)((CharacterEntityDef)Def)?.CombatEngine.Def;
            ActionEngine.Def = (IDef)((CharacterEntityDef)Def)?.ActionEngine.Def;
            StatsEngine.Def = (IDef)((CharacterEntityDef)Def)?.StatsEngine.Def;
        }

        override public void CallInitOnComponents()
        {
            _spriteRenderer.Init();
            SpellsEngine.Init();
            CombatEngine.Init();
            ActionEngine.Init();
            StatsEngine.Init();
        }

        override public void CallCreateOnComponents()
        {
            _spriteRenderer.Create();
            SpellsEngine.Create();
            CombatEngine.Create();
            ActionEngine.Create();
            StatsEngine.Create();
        }

        override public void CallDestroyOnComponents()
        {
            _spriteRenderer.Destroy();
            SpellsEngine.Destroy();
            CombatEngine.Destroy();
            ActionEngine.Destroy();
            StatsEngine.Destroy();
        }
    }

    //obj CharacterEntity generic  hasCustomSerialization false
    //debug info IEntityPropertyChanged,ICharacterLikeMovement,IRenderable,IPositionedEntity,IStatEntity,IImpactedEntity,IQuester,IHasInventory,IEntityObject,ITicked,IHasSpells,IHasActionEngine,IHasCombatEngine,IHasLocoMover 14
    [GeneratedClass]
    public partial class CharacterEntitySync : CharacterEntity, IGhost
    {
        public override Single Rotation
        {
            get => base.Rotation;
            set
            {
                base.Rotation = value;
                OnPropChanged(0);
            }
        }

        public override Int64 ActiveItemId
        {
            get => base.ActiveItemId;
            set
            {
                base.ActiveItemId = value;
                OnPropChanged(1);
            }
        }

        public override RoleDef SecretRole
        {
            get => base.SecretRole;
            set
            {
                base.SecretRole = value;
                OnPropChanged(2);
            }
        }

        public override RoleDef Job
        {
            get => base.Job;
            set
            {
                base.Job = value;
                OnPropChanged(3);
            }
        }

        public override SpellsEngine SpellsEngine
        {
            get => base.SpellsEngine;
            set
            {
                ((SyncObject)base.SpellsEngine)?.SetParentEntity(null);
                base.SpellsEngine = value;
                OnPropChanged(4);
                ((SyncObject)base.SpellsEngine)?.SetParentEntity(ParentEntity);
            }
        }

        public override SampleComponent Cmp
        {
            get => base.Cmp;
            set
            {
                ((SyncObject)base.Cmp)?.SetParentEntity(null);
                base.Cmp = value;
                OnPropChanged(5);
                ((SyncObject)base.Cmp)?.SetParentEntity(ParentEntity);
            }
        }

        public override CombatEngine CombatEngine
        {
            get => base.CombatEngine;
            set
            {
                ((SyncObject)base.CombatEngine)?.SetParentEntity(null);
                base.CombatEngine = value;
                OnPropChanged(6);
                ((SyncObject)base.CombatEngine)?.SetParentEntity(ParentEntity);
            }
        }

        public override ActionEngine ActionEngine
        {
            get => base.ActionEngine;
            set
            {
                ((SyncObject)base.ActionEngine)?.SetParentEntity(null);
                base.ActionEngine = value;
                OnPropChanged(7);
                ((SyncObject)base.ActionEngine)?.SetParentEntity(ParentEntity);
            }
        }

        public override String Name
        {
            get => base.Name;
            set
            {
                base.Name = value;
                OnPropChanged(8);
            }
        }

        public override Vec2 Position
        {
            get => base.Position;
            set
            {
                base.Position = value;
                OnPropChanged(9);
            }
        }

        public override Single Speed
        {
            get => base.Speed;
            set
            {
                base.Speed = value;
                OnPropChanged(10);
            }
        }

        public override StatsEngine StatsEngine
        {
            get => base.StatsEngine;
            set
            {
                ((SyncObject)base.StatsEngine)?.SetParentEntity(null);
                base.StatsEngine = value;
                OnPropChanged(11);
                ((SyncObject)base.StatsEngine)?.SetParentEntity(ParentEntity);
            }
        }

        public override ItemsCollection Inventory
        {
            get => base.Inventory;
            set
            {
                ((SyncObject)base.Inventory)?.SetParentEntity(null);
                base.Inventory = value;
                OnPropChanged(12);
                ((SyncObject)base.Inventory)?.SetParentEntity(ParentEntity);
            }
        }

        public override IEntityObjectDef Def
        {
            get => base.Def;
            set
            {
                base.Def = value;
                OnPropChanged(13);
            }
        }

        public override void InitFromSceneDef(BaseDef def)
        {
            var selfDef = (CharacterEntitySceneDef)def;
            _spriteRenderer.InitFromSceneDef(selfDef._spriteRenderer.Def);
            SpellsEngine.InitFromSceneDef(selfDef.SpellsEngine.Def);
            CombatEngine.InitFromSceneDef(selfDef.CombatEngine.Def);
            ActionEngine.InitFromSceneDef(selfDef.ActionEngine.Def);
            StatsEngine.InitFromSceneDef(selfDef.StatsEngine.Def);
            Rotation = selfDef.Rotation;
            Position = selfDef.Position;
        }

        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
            ((IGhost)SpellsEngine)?.ClearSerialization();
            ((IGhost)Cmp)?.ClearSerialization();
            ((IGhost)CombatEngine)?.ClearSerialization();
            ((IGhost)ActionEngine)?.ClearSerialization();
            ((IGhost)StatsEngine)?.ClearSerialization();
            ((IGhost)Inventory)?.ClearSerialization();
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, 13208307);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            CheckStream(stream, -1456363876);
            if ((mask & (1 << 0)) != 0)
            {
                CheckStream(stream, -1456363876);
                Rotation = stream.GetFloat();
                CheckStream(stream, -1456363876);
            }

            CheckStream(stream, -376406714);
            if ((mask & (1 << 1)) != 0)
            {
                CheckStream(stream, -376406714);
                ActiveItemId = stream.GetLong();
                CheckStream(stream, -376406714);
            }

            CheckStream(stream, -176050901);
            if ((mask & (1 << 2)) != 0)
            {
                CheckStream(stream, -176050901);
                var has = stream.GetBool();
                SecretRole = !has ? default : (RoleDef)SyncTypesMap.GetSerializerForObjType(typeof(RoleDef)).Deserialize(stream);
                CheckStream(stream, -176050901);
            }

            CheckStream(stream, 1858081676);
            if ((mask & (1 << 3)) != 0)
            {
                CheckStream(stream, 1858081676);
                var has = stream.GetBool();
                Job = !has ? default : (RoleDef)SyncTypesMap.GetSerializerForObjType(typeof(RoleDef)).Deserialize(stream);
                CheckStream(stream, 1858081676);
            }

            CheckStream(stream, -803283419);
            if ((mask & (1 << 4)) != 0)
            {
                CheckStream(stream, -803283419);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    SpellsEngine = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    SpellsEngine = (SpellsEngine)newVal;
                }

                CheckStream(stream, -803283419);
            }
            else
            {
                CheckStream(stream, -803283419);
                ((IGhost)SpellsEngine)?.Deserialize(stream);
                CheckStream(stream, -803283419);
            }

            CheckStream(stream, -2044727689);
            if ((mask & (1 << 5)) != 0)
            {
                CheckStream(stream, -2044727689);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    Cmp = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    Cmp = (SampleComponent)newVal;
                }

                CheckStream(stream, -2044727689);
            }
            else
            {
                CheckStream(stream, -2044727689);
                ((IGhost)Cmp)?.Deserialize(stream);
                CheckStream(stream, -2044727689);
            }

            CheckStream(stream, 421351343);
            if ((mask & (1 << 6)) != 0)
            {
                CheckStream(stream, 421351343);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    CombatEngine = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    CombatEngine = (CombatEngine)newVal;
                }

                CheckStream(stream, 421351343);
            }
            else
            {
                CheckStream(stream, 421351343);
                ((IGhost)CombatEngine)?.Deserialize(stream);
                CheckStream(stream, 421351343);
            }

            CheckStream(stream, -1128919952);
            if ((mask & (1 << 7)) != 0)
            {
                CheckStream(stream, -1128919952);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    ActionEngine = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    ActionEngine = (ActionEngine)newVal;
                }

                CheckStream(stream, -1128919952);
            }
            else
            {
                CheckStream(stream, -1128919952);
                ((IGhost)ActionEngine)?.Deserialize(stream);
                CheckStream(stream, -1128919952);
            }

            CheckStream(stream, -130991501);
            if ((mask & (1 << 8)) != 0)
            {
                CheckStream(stream, -130991501);
                Name = stream.GetString();
                CheckStream(stream, -130991501);
            }

            CheckStream(stream, 129343090);
            if ((mask & (1 << 9)) != 0)
            {
                CheckStream(stream, 129343090);
                var has = stream.GetBool();
                Position = !has ? default : (Vec2)SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Deserialize(stream);
                CheckStream(stream, 129343090);
            }

            CheckStream(stream, 844823986);
            if ((mask & (1 << 10)) != 0)
            {
                CheckStream(stream, 844823986);
                Speed = stream.GetFloat();
                CheckStream(stream, 844823986);
            }

            CheckStream(stream, -1984039357);
            if ((mask & (1 << 11)) != 0)
            {
                CheckStream(stream, -1984039357);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    StatsEngine = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    StatsEngine = (StatsEngine)newVal;
                }

                CheckStream(stream, -1984039357);
            }
            else
            {
                CheckStream(stream, -1984039357);
                ((IGhost)StatsEngine)?.Deserialize(stream);
                CheckStream(stream, -1984039357);
            }

            CheckStream(stream, -546078952);
            if ((mask & (1 << 12)) != 0)
            {
                CheckStream(stream, -546078952);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    Inventory = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    Inventory = (ItemsCollection)newVal;
                }

                CheckStream(stream, -546078952);
            }
            else
            {
                CheckStream(stream, -546078952);
                ((IGhost)Inventory)?.Deserialize(stream);
                CheckStream(stream, -546078952);
            }

            CheckStream(stream, 1164755213);
            if ((mask & (1 << 13)) != 0)
            {
                CheckStream(stream, 1164755213);
                var has = stream.GetBool();
                Def = !has ? default : (IEntityObjectDef)SyncTypesMap.GetSerializerForObjType(typeof(IEntityObjectDef)).Deserialize(stream);
                CheckStream(stream, 1164755213);
            }

            OnAfterDeserialize();
        }

        public override void SetParentEntityRecursive()
        {
            ((SyncObject)SpellsEngine)?.SetParentEntity(this.ParentEntity);
            ((SyncObject)Cmp)?.SetParentEntity(this.ParentEntity);
            ((SyncObject)CombatEngine)?.SetParentEntity(this.ParentEntity);
            ((SyncObject)ActionEngine)?.SetParentEntity(this.ParentEntity);
            ((SyncObject)StatsEngine)?.SetParentEntity(this.ParentEntity);
            ((SyncObject)Inventory)?.SetParentEntity(this.ParentEntity);
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, 13208307);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            SafeguardStream(stream, -1456363876);
            if ((deltaMask & (1 << 0)) != 0)
            {
                SafeguardStream(stream, -1456363876);
                hasAny = true;
                stream.Put(Rotation);
                SafeguardStream(stream, -1456363876);
            }

            SafeguardStream(stream, -376406714);
            if ((deltaMask & (1 << 1)) != 0)
            {
                SafeguardStream(stream, -376406714);
                hasAny = true;
                stream.Put(ActiveItemId);
                SafeguardStream(stream, -376406714);
            }

            SafeguardStream(stream, -176050901);
            if ((deltaMask & (1 << 2)) != 0)
            {
                SafeguardStream(stream, -176050901);
                hasAny = true;
                if (SecretRole != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(RoleDef)).Serialize(SecretRole, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, -176050901);
            }

            SafeguardStream(stream, 1858081676);
            if ((deltaMask & (1 << 3)) != 0)
            {
                SafeguardStream(stream, 1858081676);
                hasAny = true;
                if (Job != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(RoleDef)).Serialize(Job, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, 1858081676);
            }

            SafeguardStream(stream, -803283419);
            if ((deltaMask & (1 << 4)) != 0)
            {
                SafeguardStream(stream, -803283419);
                hasAny = true;
                if (SpellsEngine == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(SpellsEngine.GetType()));
                    ((IGhost)SpellsEngine).Serialize(ref stream, true);
                }

                SafeguardStream(stream, -803283419);
            }
            else
            {
                SafeguardStream(stream, -803283419);
                hasAny |= ((IGhost)SpellsEngine)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, -803283419);
            }

            SafeguardStream(stream, -2044727689);
            if ((deltaMask & (1 << 5)) != 0)
            {
                SafeguardStream(stream, -2044727689);
                hasAny = true;
                if (Cmp == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(Cmp.GetType()));
                    ((IGhost)Cmp).Serialize(ref stream, true);
                }

                SafeguardStream(stream, -2044727689);
            }
            else
            {
                SafeguardStream(stream, -2044727689);
                hasAny |= ((IGhost)Cmp)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, -2044727689);
            }

            SafeguardStream(stream, 421351343);
            if ((deltaMask & (1 << 6)) != 0)
            {
                SafeguardStream(stream, 421351343);
                hasAny = true;
                if (CombatEngine == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(CombatEngine.GetType()));
                    ((IGhost)CombatEngine).Serialize(ref stream, true);
                }

                SafeguardStream(stream, 421351343);
            }
            else
            {
                SafeguardStream(stream, 421351343);
                hasAny |= ((IGhost)CombatEngine)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, 421351343);
            }

            SafeguardStream(stream, -1128919952);
            if ((deltaMask & (1 << 7)) != 0)
            {
                SafeguardStream(stream, -1128919952);
                hasAny = true;
                if (ActionEngine == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(ActionEngine.GetType()));
                    ((IGhost)ActionEngine).Serialize(ref stream, true);
                }

                SafeguardStream(stream, -1128919952);
            }
            else
            {
                SafeguardStream(stream, -1128919952);
                hasAny |= ((IGhost)ActionEngine)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, -1128919952);
            }

            SafeguardStream(stream, -130991501);
            if ((deltaMask & (1 << 8)) != 0)
            {
                SafeguardStream(stream, -130991501);
                hasAny = true;
                stream.Put(Name);
                SafeguardStream(stream, -130991501);
            }

            SafeguardStream(stream, 129343090);
            if ((deltaMask & (1 << 9)) != 0)
            {
                SafeguardStream(stream, 129343090);
                hasAny = true;
                if (Position != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Serialize(Position, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, 129343090);
            }

            SafeguardStream(stream, 844823986);
            if ((deltaMask & (1 << 10)) != 0)
            {
                SafeguardStream(stream, 844823986);
                hasAny = true;
                stream.Put(Speed);
                SafeguardStream(stream, 844823986);
            }

            SafeguardStream(stream, -1984039357);
            if ((deltaMask & (1 << 11)) != 0)
            {
                SafeguardStream(stream, -1984039357);
                hasAny = true;
                if (StatsEngine == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(StatsEngine.GetType()));
                    ((IGhost)StatsEngine).Serialize(ref stream, true);
                }

                SafeguardStream(stream, -1984039357);
            }
            else
            {
                SafeguardStream(stream, -1984039357);
                hasAny |= ((IGhost)StatsEngine)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, -1984039357);
            }

            SafeguardStream(stream, -546078952);
            if ((deltaMask & (1 << 12)) != 0)
            {
                SafeguardStream(stream, -546078952);
                hasAny = true;
                if (Inventory == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(Inventory.GetType()));
                    ((IGhost)Inventory).Serialize(ref stream, true);
                }

                SafeguardStream(stream, -546078952);
            }
            else
            {
                SafeguardStream(stream, -546078952);
                hasAny |= ((IGhost)Inventory)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, -546078952);
            }

            SafeguardStream(stream, 1164755213);
            if ((deltaMask & (1 << 13)) != 0)
            {
                SafeguardStream(stream, 1164755213);
                hasAny = true;
                if (Def != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(IEntityObjectDef)).Serialize(Def, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, 1164755213);
            }

            return hasAny;
        }

        public override void SetActiveItem(long itemId)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.SetActiveItem(itemId);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new CharacterEntitySetActiveItemMessage()
                {EntityId = Id, itemId = itemId});
            }
        }

        public override void ActivateItem()
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.ActivateItem();
            }
            else
            {
                CurrentServer.HandleEntityMessage(new CharacterEntityActivateItemMessage()
                {EntityId = Id, });
            }
        }

        public override void ReceivePosition(Vec2 newPosition, float newRotation)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.ReceivePosition(newPosition, newRotation);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new CharacterEntityReceivePositionMessage()
                {EntityId = Id, newPosition = newPosition, newRotation = newRotation});
            }
        }

        public override void RunImpact(ScriptingContext originalContext, IImpactDef def)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.RunImpact(originalContext, def);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new CharacterEntityRunImpactMessage()
                {EntityId = Id, originalContext = originalContext, def = def});
            }
        }

        public override void AddItem(Item item)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.AddItem(item);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new CharacterEntityAddItemMessage()
                {EntityId = Id, item = item});
            }
        }
    }

    [GeneratedClass]
    public class CharacterEntitySetActiveItemMessage : EntityMessage
    {
        public override int NetId => 1785534715;
        public long itemId;
        public override void Run(object entity)
        {
            ((CharacterEntity)entity).SetActiveItem(itemId);
        }
    }

    [GeneratedClass]
    public class CharacterEntitySetActiveItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new CharacterEntitySetActiveItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                messageToSerialize.itemId = stream.GetLong();
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (CharacterEntitySetActiveItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                stream.Put(messageToSerialize.itemId);
            }

            return true;
        }
    }

    [GeneratedClass]
    public class CharacterEntityActivateItemMessage : EntityMessage
    {
        public override int NetId => -299944689;
        public override void Run(object entity)
        {
            ((CharacterEntity)entity).ActivateItem();
        }
    }

    [GeneratedClass]
    public class CharacterEntityActivateItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new CharacterEntityActivateItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (CharacterEntityActivateItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            return true;
        }
    }

    [GeneratedClass]
    public class CharacterEntityReceivePositionMessage : EntityMessage
    {
        public override int NetId => -1943081000;
        public Vec2 newPosition;
        public float newRotation;
        public override void Run(object entity)
        {
            ((CharacterEntity)entity).ReceivePosition(newPosition, newRotation);
        }
    }

    [GeneratedClass]
    public class CharacterEntityReceivePositionMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new CharacterEntityReceivePositionMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var has = stream.GetBool();
                messageToSerialize.newPosition = !has ? default : (Vec2)SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Deserialize(stream);
            }

            {
                messageToSerialize.newRotation = stream.GetFloat();
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (CharacterEntityReceivePositionMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.newPosition != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Serialize(messageToSerialize.newPosition, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                stream.Put(messageToSerialize.newRotation);
            }

            return true;
        }
    }

    [GeneratedClass]
    public class CharacterEntityRunImpactMessage : EntityMessage
    {
        public override int NetId => -917260775;
        public ScriptingContext originalContext;
        public IImpactDef def;
        public override void Run(object entity)
        {
            ((CharacterEntity)entity).RunImpact(originalContext, def);
        }
    }

    [GeneratedClass]
    public class CharacterEntityRunImpactMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new CharacterEntityRunImpactMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var has = stream.GetBool();
                messageToSerialize.originalContext = !has ? default : (ScriptingContext)SyncTypesMap.GetSerializerForObjType(typeof(ScriptingContext)).Deserialize(stream);
            }

            {
                var has = stream.GetBool();
                messageToSerialize.def = !has ? default : (IImpactDef)SyncTypesMap.GetSerializerForObjType(typeof(IImpactDef)).Deserialize(stream);
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (CharacterEntityRunImpactMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.originalContext != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(ScriptingContext)).Serialize(messageToSerialize.originalContext, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.def != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(IImpactDef)).Serialize(messageToSerialize.def, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            return true;
        }
    }

    [GeneratedClass]
    public class CharacterEntityAddItemMessage : EntityMessage
    {
        public override int NetId => 49904781;
        public Item item;
        public override void Run(object entity)
        {
            ((CharacterEntity)entity).AddItem(item);
        }
    }

    [GeneratedClass]
    public class CharacterEntityAddItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new CharacterEntityAddItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    messageToSerialize.item = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    messageToSerialize.item = (Item)newVal;
                }
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (CharacterEntityAddItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.item == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(messageToSerialize.item.GetType()));
                    ((IGhost)messageToSerialize.item).Serialize(ref stream, true);
                }
            }

            return true;
        }
    }
}