// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using NetworkEngine;
using CodeGen;
using SFML.Graphics;
using SFML.System;
using SFML.Window;
using System;
using System.Threading.Tasks;
using LiteNetLib.Utils;
using System.Linq;
using System.Collections.Generic;
using Volatile;
using Definitions;
using SFML.Audio;

namespace Yogollag
{
}

namespace Yogollag
{
    [GeneratedClass]
    public partial class VisibilityEntitySync
    {
        override protected void SetDefsForComponents()
        {
        }
    }

    //obj VisibilityEntity generic  hasCustomSerialization false
    //debug info IEntityPropertyChanged,ITicked 2
    [GeneratedClass]
    public partial class VisibilityEntitySync : VisibilityEntity, IGhost
    {
        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, -964957301);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
        }

        public override void SetParentEntityRecursive()
        {
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, -964957301);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            return hasAny;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public partial class SessionEntitySync
    {
        override protected void SetDefsForComponents()
        {
        }
    }

    //obj SessionEntity generic  hasCustomSerialization false
    //debug info IEntityPropertyChanged 1
    [GeneratedClass]
    public partial class SessionEntitySync : SessionEntity, IGhost
    {
        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, -1047763481);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
        }

        public override void SetParentEntityRecursive()
        {
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, -1047763481);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            return hasAny;
        }

        public override void Join(string name)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.Join(name);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new SessionEntityJoinMessage()
                {EntityId = Id, name = name});
            }
        }
    }

    [GeneratedClass]
    public class SessionEntityJoinMessage : EntityMessage
    {
        public override int NetId => 1494548524;
        public string name;
        public override void Run(object entity)
        {
            ((SessionEntity)entity).Join(name);
        }
    }

    [GeneratedClass]
    public class SessionEntityJoinMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new SessionEntityJoinMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                messageToSerialize.name = stream.GetString();
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (SessionEntityJoinMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                stream.Put(messageToSerialize.name);
            }

            return true;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public partial class SampleComponentSync
    {
        override protected void SetDefsForComponents()
        {
        }
    }

    //obj SampleComponent generic  hasCustomSerialization false
    //debug info  0
    [GeneratedClass]
    public partial class SampleComponentSync : SampleComponent, IGhost
    {
        public override Vec2 Pos
        {
            get => base.Pos;
            set
            {
                base.Pos = value;
                OnPropChanged(0);
            }
        }

        public override Vec2 PrevPos
        {
            get => base.PrevPos;
            set
            {
                base.PrevPos = value;
                OnPropChanged(1);
            }
        }

        public override Int32 SyncId
        {
            get => base.SyncId;
            set
            {
                base.SyncId = value;
                OnPropChanged(2);
            }
        }

        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, -876798592);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            CheckStream(stream, -2115009765);
            if ((mask & (1 << 0)) != 0)
            {
                CheckStream(stream, -2115009765);
                var has = stream.GetBool();
                Pos = !has ? default : (Vec2)SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Deserialize(stream);
                CheckStream(stream, -2115009765);
            }

            CheckStream(stream, -669733080);
            if ((mask & (1 << 1)) != 0)
            {
                CheckStream(stream, -669733080);
                var has = stream.GetBool();
                PrevPos = !has ? default : (Vec2)SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Deserialize(stream);
                CheckStream(stream, -669733080);
            }

            CheckStream(stream, 216020498);
            if ((mask & (1 << 2)) != 0)
            {
                CheckStream(stream, 216020498);
                SyncId = stream.GetInt();
                CheckStream(stream, 216020498);
            }
        }

        public override void SetParentEntityRecursive()
        {
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, -876798592);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            SafeguardStream(stream, -2115009765);
            if ((deltaMask & (1 << 0)) != 0)
            {
                SafeguardStream(stream, -2115009765);
                hasAny = true;
                if (Pos != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Serialize(Pos, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, -2115009765);
            }

            SafeguardStream(stream, -669733080);
            if ((deltaMask & (1 << 1)) != 0)
            {
                SafeguardStream(stream, -669733080);
                hasAny = true;
                if (PrevPos != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Serialize(PrevPos, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, -669733080);
            }

            SafeguardStream(stream, 216020498);
            if ((deltaMask & (1 << 2)) != 0)
            {
                SafeguardStream(stream, 216020498);
                hasAny = true;
                stream.Put(SyncId);
                SafeguardStream(stream, 216020498);
            }

            return hasAny;
        }

        public override void HandlePos(Vec2 newPos)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.HandlePos(newPos);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new SampleComponentHandlePosMessage()
                {EntityId = Id, newPos = newPos});
            }
        }
    }

    [GeneratedClass]
    public class SampleComponentHandlePosMessage : EntityMessage
    {
        public override int NetId => 1670033410;
        public Vec2 newPos;
        public override void Run(object entity)
        {
            ((SampleComponent)entity).HandlePos(newPos);
        }
    }

    [GeneratedClass]
    public class SampleComponentHandlePosMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new SampleComponentHandlePosMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var has = stream.GetBool();
                messageToSerialize.newPos = !has ? default : (Vec2)SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Deserialize(stream);
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (SampleComponentHandlePosMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.newPos != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Serialize(messageToSerialize.newPos, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            return true;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public partial class ItemSync
    {
        override protected void SetDefsForComponents()
        {
        }
    }

    //obj Item generic  hasCustomSerialization false
    //debug info IEntityObject 1
    [GeneratedClass]
    public partial class ItemSync : Item, IGhost
    {
        public override Int64 ItemId
        {
            get => base.ItemId;
            set
            {
                base.ItemId = value;
                OnPropChanged(0);
            }
        }

        public override ItemDef ItemDef
        {
            get => base.ItemDef;
            set
            {
                base.ItemDef = value;
                OnPropChanged(1);
            }
        }

        public override Int32 SyncId
        {
            get => base.SyncId;
            set
            {
                base.SyncId = value;
                OnPropChanged(2);
            }
        }

        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, -187496003);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            CheckStream(stream, -1106413250);
            if ((mask & (1 << 0)) != 0)
            {
                CheckStream(stream, -1106413250);
                ItemId = stream.GetLong();
                CheckStream(stream, -1106413250);
            }

            CheckStream(stream, -2065495726);
            if ((mask & (1 << 1)) != 0)
            {
                CheckStream(stream, -2065495726);
                var has = stream.GetBool();
                ItemDef = !has ? default : (ItemDef)SyncTypesMap.GetSerializerForObjType(typeof(ItemDef)).Deserialize(stream);
                CheckStream(stream, -2065495726);
            }

            CheckStream(stream, 216020498);
            if ((mask & (1 << 2)) != 0)
            {
                CheckStream(stream, 216020498);
                SyncId = stream.GetInt();
                CheckStream(stream, 216020498);
            }
        }

        public override void SetParentEntityRecursive()
        {
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, -187496003);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            SafeguardStream(stream, -1106413250);
            if ((deltaMask & (1 << 0)) != 0)
            {
                SafeguardStream(stream, -1106413250);
                hasAny = true;
                stream.Put(ItemId);
                SafeguardStream(stream, -1106413250);
            }

            SafeguardStream(stream, -2065495726);
            if ((deltaMask & (1 << 1)) != 0)
            {
                SafeguardStream(stream, -2065495726);
                hasAny = true;
                if (ItemDef != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(ItemDef)).Serialize(ItemDef, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, -2065495726);
            }

            SafeguardStream(stream, 216020498);
            if ((deltaMask & (1 << 2)) != 0)
            {
                SafeguardStream(stream, 216020498);
                hasAny = true;
                stream.Put(SyncId);
                SafeguardStream(stream, 216020498);
            }

            return hasAny;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public partial class ItemsCollectionSync
    {
        override protected void SetDefsForComponents()
        {
        }
    }

    //obj ItemsCollection generic  hasCustomSerialization false
    //debug info  0
    [GeneratedClass]
    public partial class ItemsCollectionSync : ItemsCollection, IGhost
    {
        public override Int32 Size
        {
            get => base.Size;
            set
            {
                base.Size = value;
                OnPropChanged(0);
            }
        }

        public override Int64 Counter
        {
            get => base.Counter;
            set
            {
                base.Counter = value;
                OnPropChanged(1);
            }
        }

        public override DeltaList<Item> Items
        {
            get => base.Items;
            set
            {
                ((SyncObject)base.Items)?.SetParentEntity(null);
                base.Items = value;
                OnPropChanged(2);
                ((SyncObject)base.Items)?.SetParentEntity(ParentEntity);
            }
        }

        public override Int32 SyncId
        {
            get => base.SyncId;
            set
            {
                base.SyncId = value;
                OnPropChanged(3);
            }
        }

        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
            ((IGhost)Items)?.ClearSerialization();
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, -1054485185);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            CheckStream(stream, 120743654);
            if ((mask & (1 << 0)) != 0)
            {
                CheckStream(stream, 120743654);
                Size = stream.GetInt();
                CheckStream(stream, 120743654);
            }

            CheckStream(stream, 398249365);
            if ((mask & (1 << 1)) != 0)
            {
                CheckStream(stream, 398249365);
                Counter = stream.GetLong();
                CheckStream(stream, 398249365);
            }

            CheckStream(stream, -1311725475);
            if ((mask & (1 << 2)) != 0)
            {
                CheckStream(stream, -1311725475);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    Items = null;
                }
                else
                {
                    var newVal = SyncObject.New<DeltaList<Item>>();
                    ((IGhost)newVal).Deserialize(stream);
                    Items = (DeltaList<Item>)newVal;
                }

                CheckStream(stream, -1311725475);
            }
            else
            {
                CheckStream(stream, -1311725475);
                ((IGhost)Items)?.Deserialize(stream);
                CheckStream(stream, -1311725475);
            }

            CheckStream(stream, 216020498);
            if ((mask & (1 << 3)) != 0)
            {
                CheckStream(stream, 216020498);
                SyncId = stream.GetInt();
                CheckStream(stream, 216020498);
            }
        }

        public override void SetParentEntityRecursive()
        {
            ((SyncObject)Items)?.SetParentEntity(this.ParentEntity);
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, -1054485185);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            SafeguardStream(stream, 120743654);
            if ((deltaMask & (1 << 0)) != 0)
            {
                SafeguardStream(stream, 120743654);
                hasAny = true;
                stream.Put(Size);
                SafeguardStream(stream, 120743654);
            }

            SafeguardStream(stream, 398249365);
            if ((deltaMask & (1 << 1)) != 0)
            {
                SafeguardStream(stream, 398249365);
                hasAny = true;
                stream.Put(Counter);
                SafeguardStream(stream, 398249365);
            }

            SafeguardStream(stream, -1311725475);
            if ((deltaMask & (1 << 2)) != 0)
            {
                SafeguardStream(stream, -1311725475);
                hasAny = true;
                if (Items == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    ((IGhost)Items).Serialize(ref stream, true);
                }

                SafeguardStream(stream, -1311725475);
            }
            else
            {
                SafeguardStream(stream, -1311725475);
                hasAny |= ((IGhost)Items)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, -1311725475);
            }

            SafeguardStream(stream, 216020498);
            if ((deltaMask & (1 << 3)) != 0)
            {
                SafeguardStream(stream, 216020498);
                hasAny = true;
                stream.Put(SyncId);
                SafeguardStream(stream, 216020498);
            }

            return hasAny;
        }

        public override void DropItem(Item item)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.DropItem(item);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new ItemsCollectionDropItemMessage()
                {EntityId = Id, item = item});
            }
        }

        public override void AddItem(Item item)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.AddItem(item);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new ItemsCollectionAddItemMessage()
                {EntityId = Id, item = item});
            }
        }

        public override void RemoveItem(long itemId)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.RemoveItem(itemId);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new ItemsCollectionRemoveItemMessage()
                {EntityId = Id, itemId = itemId});
            }
        }

        public override void MoveItem(long itemId, int slot)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.MoveItem(itemId, slot);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new ItemsCollectionMoveItemMessage()
                {EntityId = Id, itemId = itemId, slot = slot});
            }
        }
    }

    [GeneratedClass]
    public class ItemsCollectionDropItemMessage : EntityMessage
    {
        public override int NetId => 1515732675;
        public Item item;
        public override void Run(object entity)
        {
            ((ItemsCollection)entity).DropItem(item);
        }
    }

    [GeneratedClass]
    public class ItemsCollectionDropItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new ItemsCollectionDropItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    messageToSerialize.item = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    messageToSerialize.item = (Item)newVal;
                }
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (ItemsCollectionDropItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.item == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(messageToSerialize.item.GetType()));
                    ((IGhost)messageToSerialize.item).Serialize(ref stream, true);
                }
            }

            return true;
        }
    }

    [GeneratedClass]
    public class ItemsCollectionAddItemMessage : EntityMessage
    {
        public override int NetId => -1735567053;
        public Item item;
        public override void Run(object entity)
        {
            ((ItemsCollection)entity).AddItem(item);
        }
    }

    [GeneratedClass]
    public class ItemsCollectionAddItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new ItemsCollectionAddItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    messageToSerialize.item = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    messageToSerialize.item = (Item)newVal;
                }
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (ItemsCollectionAddItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.item == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(messageToSerialize.item.GetType()));
                    ((IGhost)messageToSerialize.item).Serialize(ref stream, true);
                }
            }

            return true;
        }
    }

    [GeneratedClass]
    public class ItemsCollectionRemoveItemMessage : EntityMessage
    {
        public override int NetId => -861032555;
        public long itemId;
        public override void Run(object entity)
        {
            ((ItemsCollection)entity).RemoveItem(itemId);
        }
    }

    [GeneratedClass]
    public class ItemsCollectionRemoveItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new ItemsCollectionRemoveItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                messageToSerialize.itemId = stream.GetLong();
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (ItemsCollectionRemoveItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                stream.Put(messageToSerialize.itemId);
            }

            return true;
        }
    }

    [GeneratedClass]
    public class ItemsCollectionMoveItemMessage : EntityMessage
    {
        public override int NetId => 1248863018;
        public long itemId;
        public int slot;
        public override void Run(object entity)
        {
            ((ItemsCollection)entity).MoveItem(itemId, slot);
        }
    }

    [GeneratedClass]
    public class ItemsCollectionMoveItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new ItemsCollectionMoveItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                messageToSerialize.itemId = stream.GetLong();
            }

            {
                messageToSerialize.slot = stream.GetInt();
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (ItemsCollectionMoveItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                stream.Put(messageToSerialize.itemId);
            }

            {
                stream.Put(messageToSerialize.slot);
            }

            return true;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public class CharacterEntitySceneDef : BaseDef, ISceneDef
    {
        public Single Rotation
        {
            get;
            set;
        }

        = default;
        public Vec2 Position
        {
            get;
            set;
        }

        = default;
        public DefRef<SpriteRendererSceneDef> _spriteRenderer
        {
            get;
            set;
        }

        = default;
        public DefRef<SpellsEngineSceneDef> SpellsEngine
        {
            get;
            set;
        }

        = default;
        public DefRef<StatsEngineSceneDef> StatsEngine
        {
            get;
            set;
        }

        = default;
    }

    [GeneratedClass]
    public class CharacterEntityDef : BaseDef, IEntityObjectDef
    {
        public DefRef<SpriteRendererDef> _spriteRenderer
        {
            get;
            set;
        }

        = default;
        public DefRef<SpellsEngineDef> SpellsEngine
        {
            get;
            set;
        }

        = default;
        public DefRef<StatsEngineDef> StatsEngine
        {
            get;
            set;
        }

        = default;
    }

    [GeneratedClass]
    public partial class CharacterEntitySync
    {
        override protected void SetDefsForComponents()
        {
            _spriteRenderer.Def = (IDef)((CharacterEntityDef)Def)?._spriteRenderer.Def;
            SpellsEngine.Def = (IDef)((CharacterEntityDef)Def)?.SpellsEngine.Def;
            StatsEngine.Def = (IDef)((CharacterEntityDef)Def)?.StatsEngine.Def;
        }
    }

    //obj CharacterEntity generic  hasCustomSerialization false
    //debug info IEntityPropertyChanged,ICharacterLikeMovement,IRenderable,IPositionedEntity,IStatEntity,IImpactedEntity,IQuester,IHasInventory,IEntityObject,ITicked,IHasSpells 11
    [GeneratedClass]
    public partial class CharacterEntitySync : CharacterEntity, IGhost
    {
        public override Single Rotation
        {
            get => base.Rotation;
            set
            {
                base.Rotation = value;
                OnPropChanged(0);
            }
        }

        public override Int64 ActiveItemId
        {
            get => base.ActiveItemId;
            set
            {
                base.ActiveItemId = value;
                OnPropChanged(1);
            }
        }

        public override RoleDef SecretRole
        {
            get => base.SecretRole;
            set
            {
                base.SecretRole = value;
                OnPropChanged(2);
            }
        }

        public override RoleDef Job
        {
            get => base.Job;
            set
            {
                base.Job = value;
                OnPropChanged(3);
            }
        }

        public override SpellsEngine SpellsEngine
        {
            get => base.SpellsEngine;
            set
            {
                ((SyncObject)base.SpellsEngine)?.SetParentEntity(null);
                base.SpellsEngine = value;
                OnPropChanged(4);
                ((SyncObject)base.SpellsEngine)?.SetParentEntity(ParentEntity);
            }
        }

        public override SampleComponent Cmp
        {
            get => base.Cmp;
            set
            {
                ((SyncObject)base.Cmp)?.SetParentEntity(null);
                base.Cmp = value;
                OnPropChanged(5);
                ((SyncObject)base.Cmp)?.SetParentEntity(ParentEntity);
            }
        }

        public override String Name
        {
            get => base.Name;
            set
            {
                base.Name = value;
                OnPropChanged(6);
            }
        }

        public override Vec2 Position
        {
            get => base.Position;
            set
            {
                base.Position = value;
                OnPropChanged(7);
            }
        }

        public override Single Speed
        {
            get => base.Speed;
            set
            {
                base.Speed = value;
                OnPropChanged(8);
            }
        }

        public override StatsEngine StatsEngine
        {
            get => base.StatsEngine;
            set
            {
                ((SyncObject)base.StatsEngine)?.SetParentEntity(null);
                base.StatsEngine = value;
                OnPropChanged(9);
                ((SyncObject)base.StatsEngine)?.SetParentEntity(ParentEntity);
            }
        }

        public override ItemsCollection Inventory
        {
            get => base.Inventory;
            set
            {
                ((SyncObject)base.Inventory)?.SetParentEntity(null);
                base.Inventory = value;
                OnPropChanged(10);
                ((SyncObject)base.Inventory)?.SetParentEntity(ParentEntity);
            }
        }

        public override IEntityObjectDef Def
        {
            get => base.Def;
            set
            {
                base.Def = value;
                OnPropChanged(11);
            }
        }

        public override void InitFromSceneDef(BaseDef def)
        {
            var selfDef = (CharacterEntitySceneDef)def;
            _spriteRenderer.InitFromSceneDef(selfDef._spriteRenderer.Def);
            SpellsEngine.InitFromSceneDef(selfDef.SpellsEngine.Def);
            StatsEngine.InitFromSceneDef(selfDef.StatsEngine.Def);
            Rotation = selfDef.Rotation;
            Position = selfDef.Position;
        }

        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
            ((IGhost)SpellsEngine)?.ClearSerialization();
            ((IGhost)Cmp)?.ClearSerialization();
            ((IGhost)StatsEngine)?.ClearSerialization();
            ((IGhost)Inventory)?.ClearSerialization();
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, 1288683405);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            CheckStream(stream, 1547229962);
            if ((mask & (1 << 0)) != 0)
            {
                CheckStream(stream, 1547229962);
                Rotation = stream.GetFloat();
                CheckStream(stream, 1547229962);
            }

            CheckStream(stream, -260695324);
            if ((mask & (1 << 1)) != 0)
            {
                CheckStream(stream, -260695324);
                ActiveItemId = stream.GetLong();
                CheckStream(stream, -260695324);
            }

            CheckStream(stream, -1682299064);
            if ((mask & (1 << 2)) != 0)
            {
                CheckStream(stream, -1682299064);
                var has = stream.GetBool();
                SecretRole = !has ? default : (RoleDef)SyncTypesMap.GetSerializerForObjType(typeof(RoleDef)).Deserialize(stream);
                CheckStream(stream, -1682299064);
            }

            CheckStream(stream, 1087255777);
            if ((mask & (1 << 3)) != 0)
            {
                CheckStream(stream, 1087255777);
                var has = stream.GetBool();
                Job = !has ? default : (RoleDef)SyncTypesMap.GetSerializerForObjType(typeof(RoleDef)).Deserialize(stream);
                CheckStream(stream, 1087255777);
            }

            CheckStream(stream, -2056676693);
            if ((mask & (1 << 4)) != 0)
            {
                CheckStream(stream, -2056676693);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    SpellsEngine = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    SpellsEngine = (SpellsEngine)newVal;
                }

                CheckStream(stream, -2056676693);
            }
            else
            {
                CheckStream(stream, -2056676693);
                ((IGhost)SpellsEngine)?.Deserialize(stream);
                CheckStream(stream, -2056676693);
            }

            CheckStream(stream, 1527330516);
            if ((mask & (1 << 5)) != 0)
            {
                CheckStream(stream, 1527330516);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    Cmp = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    Cmp = (SampleComponent)newVal;
                }

                CheckStream(stream, 1527330516);
            }
            else
            {
                CheckStream(stream, 1527330516);
                ((IGhost)Cmp)?.Deserialize(stream);
                CheckStream(stream, 1527330516);
            }

            CheckStream(stream, -1156162233);
            if ((mask & (1 << 6)) != 0)
            {
                CheckStream(stream, -1156162233);
                Name = stream.GetString();
                CheckStream(stream, -1156162233);
            }

            CheckStream(stream, -1812824421);
            if ((mask & (1 << 7)) != 0)
            {
                CheckStream(stream, -1812824421);
                var has = stream.GetBool();
                Position = !has ? default : (Vec2)SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Deserialize(stream);
                CheckStream(stream, -1812824421);
            }

            CheckStream(stream, 139840394);
            if ((mask & (1 << 8)) != 0)
            {
                CheckStream(stream, 139840394);
                Speed = stream.GetFloat();
                CheckStream(stream, 139840394);
            }

            CheckStream(stream, 139269288);
            if ((mask & (1 << 9)) != 0)
            {
                CheckStream(stream, 139269288);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    StatsEngine = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    StatsEngine = (StatsEngine)newVal;
                }

                CheckStream(stream, 139269288);
            }
            else
            {
                CheckStream(stream, 139269288);
                ((IGhost)StatsEngine)?.Deserialize(stream);
                CheckStream(stream, 139269288);
            }

            CheckStream(stream, -1195681167);
            if ((mask & (1 << 10)) != 0)
            {
                CheckStream(stream, -1195681167);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    Inventory = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    Inventory = (ItemsCollection)newVal;
                }

                CheckStream(stream, -1195681167);
            }
            else
            {
                CheckStream(stream, -1195681167);
                ((IGhost)Inventory)?.Deserialize(stream);
                CheckStream(stream, -1195681167);
            }

            CheckStream(stream, -652744550);
            if ((mask & (1 << 11)) != 0)
            {
                CheckStream(stream, -652744550);
                var has = stream.GetBool();
                Def = !has ? default : (IEntityObjectDef)SyncTypesMap.GetSerializerForObjType(typeof(IEntityObjectDef)).Deserialize(stream);
                CheckStream(stream, -652744550);
            }
        }

        public override void SetParentEntityRecursive()
        {
            ((SyncObject)SpellsEngine)?.SetParentEntity(this.ParentEntity);
            ((SyncObject)Cmp)?.SetParentEntity(this.ParentEntity);
            ((SyncObject)StatsEngine)?.SetParentEntity(this.ParentEntity);
            ((SyncObject)Inventory)?.SetParentEntity(this.ParentEntity);
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, 1288683405);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            SafeguardStream(stream, 1547229962);
            if ((deltaMask & (1 << 0)) != 0)
            {
                SafeguardStream(stream, 1547229962);
                hasAny = true;
                stream.Put(Rotation);
                SafeguardStream(stream, 1547229962);
            }

            SafeguardStream(stream, -260695324);
            if ((deltaMask & (1 << 1)) != 0)
            {
                SafeguardStream(stream, -260695324);
                hasAny = true;
                stream.Put(ActiveItemId);
                SafeguardStream(stream, -260695324);
            }

            SafeguardStream(stream, -1682299064);
            if ((deltaMask & (1 << 2)) != 0)
            {
                SafeguardStream(stream, -1682299064);
                hasAny = true;
                if (SecretRole != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(RoleDef)).Serialize(SecretRole, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, -1682299064);
            }

            SafeguardStream(stream, 1087255777);
            if ((deltaMask & (1 << 3)) != 0)
            {
                SafeguardStream(stream, 1087255777);
                hasAny = true;
                if (Job != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(RoleDef)).Serialize(Job, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, 1087255777);
            }

            SafeguardStream(stream, -2056676693);
            if ((deltaMask & (1 << 4)) != 0)
            {
                SafeguardStream(stream, -2056676693);
                hasAny = true;
                if (SpellsEngine == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(SpellsEngine.GetType()));
                    ((IGhost)SpellsEngine).Serialize(ref stream, true);
                }

                SafeguardStream(stream, -2056676693);
            }
            else
            {
                SafeguardStream(stream, -2056676693);
                hasAny |= ((IGhost)SpellsEngine)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, -2056676693);
            }

            SafeguardStream(stream, 1527330516);
            if ((deltaMask & (1 << 5)) != 0)
            {
                SafeguardStream(stream, 1527330516);
                hasAny = true;
                if (Cmp == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(Cmp.GetType()));
                    ((IGhost)Cmp).Serialize(ref stream, true);
                }

                SafeguardStream(stream, 1527330516);
            }
            else
            {
                SafeguardStream(stream, 1527330516);
                hasAny |= ((IGhost)Cmp)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, 1527330516);
            }

            SafeguardStream(stream, -1156162233);
            if ((deltaMask & (1 << 6)) != 0)
            {
                SafeguardStream(stream, -1156162233);
                hasAny = true;
                stream.Put(Name);
                SafeguardStream(stream, -1156162233);
            }

            SafeguardStream(stream, -1812824421);
            if ((deltaMask & (1 << 7)) != 0)
            {
                SafeguardStream(stream, -1812824421);
                hasAny = true;
                if (Position != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Serialize(Position, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, -1812824421);
            }

            SafeguardStream(stream, 139840394);
            if ((deltaMask & (1 << 8)) != 0)
            {
                SafeguardStream(stream, 139840394);
                hasAny = true;
                stream.Put(Speed);
                SafeguardStream(stream, 139840394);
            }

            SafeguardStream(stream, 139269288);
            if ((deltaMask & (1 << 9)) != 0)
            {
                SafeguardStream(stream, 139269288);
                hasAny = true;
                if (StatsEngine == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(StatsEngine.GetType()));
                    ((IGhost)StatsEngine).Serialize(ref stream, true);
                }

                SafeguardStream(stream, 139269288);
            }
            else
            {
                SafeguardStream(stream, 139269288);
                hasAny |= ((IGhost)StatsEngine)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, 139269288);
            }

            SafeguardStream(stream, -1195681167);
            if ((deltaMask & (1 << 10)) != 0)
            {
                SafeguardStream(stream, -1195681167);
                hasAny = true;
                if (Inventory == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(Inventory.GetType()));
                    ((IGhost)Inventory).Serialize(ref stream, true);
                }

                SafeguardStream(stream, -1195681167);
            }
            else
            {
                SafeguardStream(stream, -1195681167);
                hasAny |= ((IGhost)Inventory)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, -1195681167);
            }

            SafeguardStream(stream, -652744550);
            if ((deltaMask & (1 << 11)) != 0)
            {
                SafeguardStream(stream, -652744550);
                hasAny = true;
                if (Def != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(IEntityObjectDef)).Serialize(Def, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, -652744550);
            }

            return hasAny;
        }

        public override void SetActiveItem(long itemId)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.SetActiveItem(itemId);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new CharacterEntitySetActiveItemMessage()
                {EntityId = Id, itemId = itemId});
            }
        }

        public override void ActivateItem()
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.ActivateItem();
            }
            else
            {
                CurrentServer.HandleEntityMessage(new CharacterEntityActivateItemMessage()
                {EntityId = Id, });
            }
        }

        public override void ReceivePosition(Vec2 newPosition)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.ReceivePosition(newPosition);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new CharacterEntityReceivePositionMessage()
                {EntityId = Id, newPosition = newPosition});
            }
        }

        public override void RunImpact(ScriptingContext originalContext, IImpactDef def)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.RunImpact(originalContext, def);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new CharacterEntityRunImpactMessage()
                {EntityId = Id, originalContext = originalContext, def = def});
            }
        }

        public override void AddItem(Item item)
        {
            if (ParentEntity.IsCurrentlyExecuting)
            {
                base.AddItem(item);
            }
            else
            {
                CurrentServer.HandleEntityMessage(new CharacterEntityAddItemMessage()
                {EntityId = Id, item = item});
            }
        }
    }

    [GeneratedClass]
    public class CharacterEntitySetActiveItemMessage : EntityMessage
    {
        public override int NetId => 213636546;
        public long itemId;
        public override void Run(object entity)
        {
            ((CharacterEntity)entity).SetActiveItem(itemId);
        }
    }

    [GeneratedClass]
    public class CharacterEntitySetActiveItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new CharacterEntitySetActiveItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                messageToSerialize.itemId = stream.GetLong();
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (CharacterEntitySetActiveItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                stream.Put(messageToSerialize.itemId);
            }

            return true;
        }
    }

    [GeneratedClass]
    public class CharacterEntityActivateItemMessage : EntityMessage
    {
        public override int NetId => -810277230;
        public override void Run(object entity)
        {
            ((CharacterEntity)entity).ActivateItem();
        }
    }

    [GeneratedClass]
    public class CharacterEntityActivateItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new CharacterEntityActivateItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (CharacterEntityActivateItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            return true;
        }
    }

    [GeneratedClass]
    public class CharacterEntityReceivePositionMessage : EntityMessage
    {
        public override int NetId => -1832822519;
        public Vec2 newPosition;
        public override void Run(object entity)
        {
            ((CharacterEntity)entity).ReceivePosition(newPosition);
        }
    }

    [GeneratedClass]
    public class CharacterEntityReceivePositionMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new CharacterEntityReceivePositionMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var has = stream.GetBool();
                messageToSerialize.newPosition = !has ? default : (Vec2)SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Deserialize(stream);
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (CharacterEntityReceivePositionMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.newPosition != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(Vec2)).Serialize(messageToSerialize.newPosition, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            return true;
        }
    }

    [GeneratedClass]
    public class CharacterEntityRunImpactMessage : EntityMessage
    {
        public override int NetId => 1453337631;
        public ScriptingContext originalContext;
        public IImpactDef def;
        public override void Run(object entity)
        {
            ((CharacterEntity)entity).RunImpact(originalContext, def);
        }
    }

    [GeneratedClass]
    public class CharacterEntityRunImpactMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new CharacterEntityRunImpactMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var has = stream.GetBool();
                messageToSerialize.originalContext = !has ? default : (ScriptingContext)SyncTypesMap.GetSerializerForObjType(typeof(ScriptingContext)).Deserialize(stream);
            }

            {
                var has = stream.GetBool();
                messageToSerialize.def = !has ? default : (IImpactDef)SyncTypesMap.GetSerializerForObjType(typeof(IImpactDef)).Deserialize(stream);
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (CharacterEntityRunImpactMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.originalContext != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(ScriptingContext)).Serialize(messageToSerialize.originalContext, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.def != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(IImpactDef)).Serialize(messageToSerialize.def, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            return true;
        }
    }

    [GeneratedClass]
    public class CharacterEntityAddItemMessage : EntityMessage
    {
        public override int NetId => 422378009;
        public Item item;
        public override void Run(object entity)
        {
            ((CharacterEntity)entity).AddItem(item);
        }
    }

    [GeneratedClass]
    public class CharacterEntityAddItemMessageSync : IGhostLikeSerializer
    {
        public object Deserialize(NetDataReader stream)
        {
            var messageToSerialize = new CharacterEntityAddItemMessage();
            {
                var has = stream.GetBool();
                messageToSerialize.EntityId = !has ? default : (EntityId)SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Deserialize(stream);
            }

            {
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    messageToSerialize.item = null;
                }
                else
                {
                    var newVal = Activator.CreateInstance(SyncTypesMap.GetSyncTypeFromId(stream.GetInt()));
                    ((IGhost)newVal).Deserialize(stream);
                    messageToSerialize.item = (Item)newVal;
                }
            }

            return messageToSerialize;
        }

        public bool Serialize(object objToSerialize, ref NetDataWriter stream)
        {
            var messageToSerialize = (CharacterEntityAddItemMessage)objToSerialize;
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            {
                if (messageToSerialize.EntityId != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(EntityId)).Serialize(messageToSerialize.EntityId, ref stream);
                }
                else
                {
                    stream.Put(false);
                }
            }

            {
                if (messageToSerialize.item == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    stream.Put(SyncTypesMap.GetIdFromSyncType(messageToSerialize.item.GetType()));
                    ((IGhost)messageToSerialize.item).Serialize(ref stream, true);
                }
            }

            return true;
        }
    }
}