// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using CodeGen;
using Definitions;
using NetworkEngine;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using LiteNetLib.Utils;

namespace Yogollag
{
    [GeneratedClass]
    public partial class AccumulatedStatSync
    {
        override protected void SetDefsForComponents()
        {
        }

        override public void CallInitOnComponents()
        {
        }

        override public void CallCreateOnComponents()
        {
        }

        override public void CallDestroyOnComponents()
        {
        }
    }

    //obj AccumulatedStat generic  hasCustomSerialization false
    //debug info  0
    [GeneratedClass]
    public partial class AccumulatedStatSync : AccumulatedStat, IGhost
    {
        public override DeltaList<AccStatModifier> Modifiers
        {
            get => base.Modifiers;
            set
            {
                ((SyncObject)base.Modifiers)?.SetParentEntity(null);
                base.Modifiers = value;
                OnPropChanged(0);
                ((SyncObject)base.Modifiers)?.SetParentEntity(ParentEntity);
            }
        }

        public override StatDef StatDef
        {
            get => base.StatDef;
            set
            {
                base.StatDef = value;
                OnPropChanged(1);
            }
        }

        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
            ((IGhost)Modifiers)?.ClearSerialization();
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, 1582635445);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            CheckStream(stream, 412861597);
            if ((mask & (1 << 0)) != 0)
            {
                CheckStream(stream, 412861597);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    Modifiers = null;
                }
                else
                {
                    var newVal = SyncObject.New<DeltaList<AccStatModifier>>();
                    ((IGhost)newVal).Deserialize(stream);
                    Modifiers = (DeltaList<AccStatModifier>)newVal;
                }

                CheckStream(stream, 412861597);
            }
            else
            {
                CheckStream(stream, 412861597);
                ((IGhost)Modifiers)?.Deserialize(stream);
                CheckStream(stream, 412861597);
            }

            CheckStream(stream, 2145825267);
            if ((mask & (1 << 1)) != 0)
            {
                CheckStream(stream, 2145825267);
                var has = stream.GetBool();
                StatDef = !has ? default : (StatDef)SyncTypesMap.GetSerializerForObjType(typeof(StatDef)).Deserialize(stream);
                CheckStream(stream, 2145825267);
            }

            OnAfterDeserialize();
        }

        public override void SetParentEntityRecursive()
        {
            ((SyncObject)Modifiers)?.SetParentEntity(this.ParentEntity);
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, 1582635445);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            SafeguardStream(stream, 412861597);
            if ((deltaMask & (1 << 0)) != 0)
            {
                SafeguardStream(stream, 412861597);
                hasAny = true;
                if (Modifiers == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    ((IGhost)Modifiers).Serialize(ref stream, true);
                }

                SafeguardStream(stream, 412861597);
            }
            else
            {
                SafeguardStream(stream, 412861597);
                hasAny |= ((IGhost)Modifiers)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, 412861597);
            }

            SafeguardStream(stream, 2145825267);
            if ((deltaMask & (1 << 1)) != 0)
            {
                SafeguardStream(stream, 2145825267);
                hasAny = true;
                if (StatDef != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(StatDef)).Serialize(StatDef, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, 2145825267);
            }

            return hasAny;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public partial class LinearStatSync
    {
        override protected void SetDefsForComponents()
        {
        }

        override public void CallInitOnComponents()
        {
        }

        override public void CallCreateOnComponents()
        {
        }

        override public void CallDestroyOnComponents()
        {
        }
    }

    //obj LinearStat generic  hasCustomSerialization false
    //debug info  0
    [GeneratedClass]
    public partial class LinearStatSync : LinearStat, IGhost
    {
        public override Single BreakpointValue
        {
            get => base.BreakpointValue;
            set
            {
                base.BreakpointValue = value;
                OnPropChanged(0);
            }
        }

        public override Int64 BreakpointTime
        {
            get => base.BreakpointTime;
            set
            {
                base.BreakpointTime = value;
                OnPropChanged(1);
            }
        }

        public override Single ChangeRate
        {
            get => base.ChangeRate;
            set
            {
                base.ChangeRate = value;
                OnPropChanged(2);
            }
        }

        public override StatDef StatDef
        {
            get => base.StatDef;
            set
            {
                base.StatDef = value;
                OnPropChanged(3);
            }
        }

        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, 1825350433);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            CheckStream(stream, 124444863);
            if ((mask & (1 << 0)) != 0)
            {
                CheckStream(stream, 124444863);
                BreakpointValue = stream.GetFloat();
                CheckStream(stream, 124444863);
            }

            CheckStream(stream, -666130446);
            if ((mask & (1 << 1)) != 0)
            {
                CheckStream(stream, -666130446);
                BreakpointTime = stream.GetLong();
                CheckStream(stream, -666130446);
            }

            CheckStream(stream, 734715995);
            if ((mask & (1 << 2)) != 0)
            {
                CheckStream(stream, 734715995);
                ChangeRate = stream.GetFloat();
                CheckStream(stream, 734715995);
            }

            CheckStream(stream, 2145825267);
            if ((mask & (1 << 3)) != 0)
            {
                CheckStream(stream, 2145825267);
                var has = stream.GetBool();
                StatDef = !has ? default : (StatDef)SyncTypesMap.GetSerializerForObjType(typeof(StatDef)).Deserialize(stream);
                CheckStream(stream, 2145825267);
            }

            OnAfterDeserialize();
        }

        public override void SetParentEntityRecursive()
        {
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, 1825350433);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            SafeguardStream(stream, 124444863);
            if ((deltaMask & (1 << 0)) != 0)
            {
                SafeguardStream(stream, 124444863);
                hasAny = true;
                stream.Put(BreakpointValue);
                SafeguardStream(stream, 124444863);
            }

            SafeguardStream(stream, -666130446);
            if ((deltaMask & (1 << 1)) != 0)
            {
                SafeguardStream(stream, -666130446);
                hasAny = true;
                stream.Put(BreakpointTime);
                SafeguardStream(stream, -666130446);
            }

            SafeguardStream(stream, 734715995);
            if ((deltaMask & (1 << 2)) != 0)
            {
                SafeguardStream(stream, 734715995);
                hasAny = true;
                stream.Put(ChangeRate);
                SafeguardStream(stream, 734715995);
            }

            SafeguardStream(stream, 2145825267);
            if ((deltaMask & (1 << 3)) != 0)
            {
                SafeguardStream(stream, 2145825267);
                hasAny = true;
                if (StatDef != default)
                {
                    stream.Put(true);
                    SyncTypesMap.GetSerializerForObjType(typeof(StatDef)).Serialize(StatDef, ref stream);
                }
                else
                {
                    stream.Put(false);
                }

                SafeguardStream(stream, 2145825267);
            }

            return hasAny;
        }
    }
}

namespace Yogollag
{
    [GeneratedClass]
    public class StatsEngineSceneDef : BaseDef, ISceneDef
    {
    }

    [GeneratedClass]
    public class StatsEngineDef : BaseDef, IEntityObjectDef
    {
        public List<DefRef<StatInstanceDef>> Stats
        {
            get;
            set;
        }

        = new List<DefRef<StatInstanceDef>>();
    }

    [GeneratedClass]
    public partial class StatsEngineSync
    {
        public override List<DefRef<StatInstanceDef>> Stats
        {
            get => ((StatsEngineDef)Def).Stats;
        }

        override protected void SetDefsForComponents()
        {
        }

        override public void CallInitOnComponents()
        {
        }

        override public void CallCreateOnComponents()
        {
        }

        override public void CallDestroyOnComponents()
        {
        }
    }

    //obj StatsEngine generic  hasCustomSerialization false
    //debug info IEntityComponent 1
    [GeneratedClass]
    public partial class StatsEngineSync : StatsEngine, IGhost
    {
        public override DeltaList<BaseStat> StatsSync
        {
            get => base.StatsSync;
            set
            {
                ((SyncObject)base.StatsSync)?.SetParentEntity(null);
                base.StatsSync = value;
                OnPropChanged(0);
                ((SyncObject)base.StatsSync)?.SetParentEntity(ParentEntity);
            }
        }

        public override Int32 SyncId
        {
            get => base.SyncId;
            set
            {
                base.SyncId = value;
                OnPropChanged(1);
            }
        }

        public override void InitFromSceneDef(BaseDef def)
        {
            var selfDef = (StatsEngineSceneDef)def;
        }

        int _deltaMask;
        public void ClearSerialization()
        {
            _deltaMask = 0;
            ((IGhost)StatsSync)?.ClearSerialization();
        }

        public void Deserialize(NetDataReader stream)
        {
            CheckStream(stream, -1905662910);
            //var hasAny = stream.GetBool();
            //if(!hasAny)
            //    return;
            var mask = stream.GetInt();
            CheckStream(stream, 1935791193);
            if ((mask & (1 << 0)) != 0)
            {
                CheckStream(stream, 1935791193);
                var nullOrNot = stream.GetByte();
                if (nullOrNot == 0)
                {
                    StatsSync = null;
                }
                else
                {
                    var newVal = SyncObject.New<DeltaList<BaseStat>>();
                    ((IGhost)newVal).Deserialize(stream);
                    StatsSync = (DeltaList<BaseStat>)newVal;
                }

                CheckStream(stream, 1935791193);
            }
            else
            {
                CheckStream(stream, 1935791193);
                ((IGhost)StatsSync)?.Deserialize(stream);
                CheckStream(stream, 1935791193);
            }

            CheckStream(stream, 818510529);
            if ((mask & (1 << 1)) != 0)
            {
                CheckStream(stream, 818510529);
                SyncId = stream.GetInt();
                CheckStream(stream, 818510529);
            }

            OnAfterDeserialize();
        }

        public override void SetParentEntityRecursive()
        {
            ((SyncObject)StatsSync)?.SetParentEntity(this.ParentEntity);
        }

        void OnPropChanged(int prop)
        {
            _deltaMask |= 1 << prop;
        }

        public bool Serialize(ref NetDataWriter stream, bool initial)
        {
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            SafeguardStream(stream, -1905662910);
            bool hasAny = false;
            int deltaMask = _deltaMask;
            if (initial)
                deltaMask = int.MaxValue;
            /*if(deltaMask == 0)
                    {
                        if(stream != null)
                            stream.Put(false);
                        return false;
                    }*/
            if (stream == null)
                stream = new NetDataWriter(true, 5);
            //stream.Put(true);
            stream.Put(deltaMask);
            SafeguardStream(stream, 1935791193);
            if ((deltaMask & (1 << 0)) != 0)
            {
                SafeguardStream(stream, 1935791193);
                hasAny = true;
                if (StatsSync == null)
                    stream.Put((byte)0);
                else
                {
                    stream.Put((byte)1);
                    ((IGhost)StatsSync).Serialize(ref stream, true);
                }

                SafeguardStream(stream, 1935791193);
            }
            else
            {
                SafeguardStream(stream, 1935791193);
                hasAny |= ((IGhost)StatsSync)?.Serialize(ref stream, initial) ?? false;
                SafeguardStream(stream, 1935791193);
            }

            SafeguardStream(stream, 818510529);
            if ((deltaMask & (1 << 1)) != 0)
            {
                SafeguardStream(stream, 818510529);
                hasAny = true;
                stream.Put(SyncId);
                SafeguardStream(stream, 818510529);
            }

            return hasAny;
        }
    }
}